// <auto-generated />
using System;
using Factura.AccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Factura.AccesoDatos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Factura.Entidades.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Factura.Entidades.ClienteHotel", b =>
                {
                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId", "HotelId");

                    b.HasIndex("HotelId");

                    b.ToTable("ClienteHotel");
                });

            modelBuilder.Entity("Factura.Entidades.Factur", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientesClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<int?>("RecepcionistaId")
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.HasIndex("ClientesClienteId");

                    b.HasIndex("HotelId");

                    b.HasIndex("RecepcionistaId");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Factura.Entidades.Habitacion", b =>
                {
                    b.Property<int>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Camas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HabitacionId");

                    b.ToTable("Habitacion");
                });

            modelBuilder.Entity("Factura.Entidades.HabitacionFactura", b =>
                {
                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.HasKey("HabitacionId", "FacturaId");

                    b.HasIndex("FacturaId");

                    b.ToTable("HabitacionFactura");
                });

            modelBuilder.Entity("Factura.Entidades.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Altura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plantas")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelId");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("Factura.Entidades.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialId");

                    b.HasIndex("HotelId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("Factura.Entidades.Recepcionista", b =>
                {
                    b.Property<int>("RecepcionistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sueldo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecepcionistaId");

                    b.HasIndex("HotelId");

                    b.ToTable("Recepcionista");
                });

            modelBuilder.Entity("Factura.Entidades.ClienteHotel", b =>
                {
                    b.HasOne("Factura.Entidades.Cliente", "Clientes")
                        .WithMany("Hoteles")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Factura.Entidades.Hotel", "Hoteles")
                        .WithMany("Clientes")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Factura.Entidades.Factur", b =>
                {
                    b.HasOne("Factura.Entidades.Cliente", "Clientes")
                        .WithMany("Factura")
                        .HasForeignKey("ClientesClienteId");

                    b.HasOne("Factura.Entidades.Hotel", "Hotel")
                        .WithMany("Facturas")
                        .HasForeignKey("HotelId");

                    b.HasOne("Factura.Entidades.Recepcionista", "Recepcionista")
                        .WithMany("Factura")
                        .HasForeignKey("RecepcionistaId");
                });

            modelBuilder.Entity("Factura.Entidades.HabitacionFactura", b =>
                {
                    b.HasOne("Factura.Entidades.Factur", "Factura")
                        .WithMany("Habitacion")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Factura.Entidades.Habitacion", "Habitaciones")
                        .WithMany("Factura")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Factura.Entidades.Material", b =>
                {
                    b.HasOne("Factura.Entidades.Hotel", null)
                        .WithMany("Materiales")
                        .HasForeignKey("HotelId");
                });

            modelBuilder.Entity("Factura.Entidades.Recepcionista", b =>
                {
                    b.HasOne("Factura.Entidades.Hotel", null)
                        .WithMany("Personal")
                        .HasForeignKey("HotelId");
                });
#pragma warning restore 612, 618
        }
    }
}
